### ISSUE TITLE
一些功能无法使用

### ISSUE THREAD

**Issue by xhzkp** [gofrp/tiny-frpc#34]
### Describe the feature request

https://github.com/fatedier/frp/issues/4332
FRPC已达15M+, 体积太大了, 所以找到了这个精简版, 但是使用tiny-frpc后, 上面链接中的面板功能不可用, 下面这些条目都不支持, 无解吗? 
只是想把exe体积变小一些, 用不到的功能去掉, 控制在一半的体积大小就好了 

```
user = "frp1"
metadatas.token = "5i365frp1"

# 加密
transport.useEncryption = true
# 压缩
transport.useCompression = true
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by blizard863** [comment]
https://github.com/gofrp/tiny-frpc/blob/main/conf/frpc_full_example.toml

支持的配置都在这里。
