### ISSUE TITLE
Does this support the frpc http_proxy proxy plug-in?

### ISSUE THREAD

**Issue by siebertkhyleez** [gofrp/tiny-frpc#8]
Does this support the frpc http_proxy proxy plug-in?

**Comment by siebertkhyleez** [comment]
[[proxies]]
name = "plugin_http_proxy"
type = "tcp"
remotePort = 6004
[proxies.plugin]
type = "http_proxy"
httpUser = "abc"
httpPassword = "abc"

**Comment by blizard863** [comment]
No support, it only support tcp/http/https/tcpmux/stcp, the full config is https://github.com/gofrp/tiny-frpc/blob/main/conf/frpc_full_example.toml
